/**
 * VYTHERA Mod Studio Backlog Checklist Status (Items 1–500).
 * Reflects strict data-driven modding status, safety guarantees, and features.
 */

export type BacklogStatus = 'done' | 'skipped' | 'blocked';

export interface BacklogItem {
  id: number;
  section: string;
  name: string;
  status: BacklogStatus;
  note?: string;
}

export const BACKLOG_ITEMS: BacklogItem[] = [
  // ══ P0 CORE 1–25 ══
  { id: 1, section: 'P0 Core', name: 'New Mod wizard', status: 'done' },
  { id: 2, section: 'P0 Core', name: 'Save', status: 'done' },
  { id: 3, section: 'P0 Core', name: 'Save As', status: 'done' },
  { id: 4, section: 'P0 Core', name: 'Autosave 30s', status: 'done' },
  { id: 5, section: 'P0 Core', name: 'Open', status: 'done' },
  { id: 6, section: 'P0 Core', name: 'Duplicate', status: 'done' },
  { id: 7, section: 'P0 Core', name: 'Delete', status: 'done' },
  { id: 8, section: 'P0 Core', name: 'Rename', status: 'done' },
  { id: 9, section: 'P0 Core', name: 'Export zip', status: 'done', note: '.vymod.json / package' },
  { id: 10, section: 'P0 Core', name: 'Import zip', status: 'done', note: '.vymod.json import' },
  { id: 11, section: 'P0 Core', name: 'Enable toggle', status: 'done' },
  { id: 12, section: 'P0 Core', name: 'Custom block 16² faces', status: 'done' },
  { id: 13, section: 'P0 Core', name: 'Hardness', status: 'done' },
  { id: 14, section: 'P0 Core', name: 'Tool type', status: 'done' },
  { id: 15, section: 'P0 Core', name: 'Block drop', status: 'done' },
  { id: 16, section: 'P0 Core', name: 'Block in picker', status: 'done' },
  { id: 17, section: 'P0 Core', name: 'Place', status: 'done' },
  { id: 18, section: 'P0 Core', name: 'Break', status: 'done' },
  { id: 19, section: 'P0 Core', name: 'Persist edits', status: 'done' },
  { id: 20, section: 'P0 Core', name: 'Custom item', status: 'done' },
  { id: 21, section: 'P0 Core', name: '2×2 recipes', status: 'done' },
  { id: 22, section: 'P0 Core', name: '3×3 recipes', status: 'done' },
  { id: 23, section: 'P0 Core', name: 'Test Play', status: 'done' },
  { id: 24, section: 'P0 Core', name: 'Validate mod.json', status: 'done' },
  { id: 25, section: 'P0 Core', name: 'VYTHERA chrome + phone + styled file input', status: 'done' },

  // ══ P1 VOXEL EDITOR 26–100 ══
  { id: 26, section: 'P1 Voxel Editor', name: '16³ canvas', status: 'done' },
  { id: 27, section: 'P1 Voxel Editor', name: '32³ cap', status: 'done' },
  { id: 28, section: 'P1 Voxel Editor', name: '8³ mobile cap', status: 'done' },
  { id: 29, section: 'P1 Voxel Editor', name: 'Brush', status: 'done' },
  { id: 30, section: 'P1 Voxel Editor', name: 'Erase', status: 'done' },
  { id: 31, section: 'P1 Voxel Editor', name: 'Fill', status: 'done' },
  { id: 32, section: 'P1 Voxel Editor', name: 'Line', status: 'done' },
  { id: 33, section: 'P1 Voxel Editor', name: 'Pick', status: 'done' },
  { id: 34, section: 'P1 Voxel Editor', name: 'Spray', status: 'done' },
  { id: 35, section: 'P1 Voxel Editor', name: 'Box draw', status: 'done' },
  { id: 36, section: 'P1 Voxel Editor', name: 'Per-face paint', status: 'done' },
  { id: 37, section: 'P1 Voxel Editor', name: 'Project paint', status: 'done' },
  { id: 38, section: 'P1 Voxel Editor', name: 'UV 8', status: 'done' },
  { id: 39, section: 'P1 Voxel Editor', name: 'UV 16', status: 'done' },
  { id: 40, section: 'P1 Voxel Editor', name: 'UV 32', status: 'done' },
  { id: 41, section: 'P1 Voxel Editor', name: 'Flip X', status: 'done' },
  { id: 42, section: 'P1 Voxel Editor', name: 'Flip Z', status: 'done' },
  { id: 43, section: 'P1 Voxel Editor', name: 'Flip Y', status: 'done' },
  { id: 44, section: 'P1 Voxel Editor', name: 'Rot X', status: 'done' },
  { id: 45, section: 'P1 Voxel Editor', name: 'Rot Y', status: 'done' },
  { id: 46, section: 'P1 Voxel Editor', name: 'Rot Z', status: 'done' },
  { id: 47, section: 'P1 Voxel Editor', name: 'Floor', status: 'done' },
  { id: 48, section: 'P1 Voxel Editor', name: 'Ceiling', status: 'done' },
  { id: 49, section: 'P1 Voxel Editor', name: 'Hollow', status: 'done' },
  { id: 50, section: 'P1 Voxel Editor', name: 'Solid fill', status: 'done' },
  { id: 51, section: 'P1 Voxel Editor', name: 'Dup', status: 'done' },
  { id: 52, section: 'P1 Voxel Editor', name: 'Copy', status: 'done' },
  { id: 53, section: 'P1 Voxel Editor', name: 'Paste', status: 'done' },
  { id: 54, section: 'P1 Voxel Editor', name: 'Cut', status: 'done' },
  { id: 55, section: 'P1 Voxel Editor', name: 'Mirror X', status: 'done' },
  { id: 56, section: 'P1 Voxel Editor', name: 'Mirror Z', status: 'done' },
  { id: 57, section: 'P1 Voxel Editor', name: 'Mirror Y', status: 'done' },
  { id: 58, section: 'P1 Voxel Editor', name: 'Selection', status: 'done' },
  { id: 59, section: 'P1 Voxel Editor', name: 'Grow', status: 'done' },
  { id: 60, section: 'P1 Voxel Editor', name: 'Shrink', status: 'done' },
  { id: 61, section: 'P1 Voxel Editor', name: 'Flood replace', status: 'done' },
  { id: 62, section: 'P1 Voxel Editor', name: 'Recolor', status: 'done' },
  { id: 63, section: 'P1 Voxel Editor', name: 'Hue', status: 'done' },
  { id: 64, section: 'P1 Voxel Editor', name: 'Saturation', status: 'done' },
  { id: 65, section: 'P1 Voxel Editor', name: 'Contrast', status: 'done' },
  { id: 66, section: 'P1 Voxel Editor', name: 'Palette lock', status: 'done' },
  { id: 67, section: 'P1 Voxel Editor', name: 'Eyedrop 3D', status: 'done' },
  { id: 68, section: 'P1 Voxel Editor', name: 'Eyedrop atlas', status: 'done' },
  { id: 69, section: 'P1 Voxel Editor', name: 'Layer add', status: 'done' },
  { id: 70, section: 'P1 Voxel Editor', name: 'Layer del', status: 'done' },
  { id: 71, section: 'P1 Voxel Editor', name: 'Layer hide', status: 'done' },
  { id: 72, section: 'P1 Voxel Editor', name: 'Layer lock', status: 'done' },
  { id: 73, section: 'P1 Voxel Editor', name: 'Layer merge', status: 'done' },
  { id: 74, section: 'P1 Voxel Editor', name: 'Undo 32', status: 'done' },
  { id: 75, section: 'P1 Voxel Editor', name: 'Redo 32', status: 'done' },
  { id: 76, section: 'P1 Voxel Editor', name: 'Undo 64 desktop', status: 'done' },
  { id: 77, section: 'P1 Voxel Editor', name: 'Grid', status: 'done' },
  { id: 78, section: 'P1 Voxel Editor', name: 'Outline', status: 'done' },
  { id: 79, section: 'P1 Voxel Editor', name: 'Axes gizmo', status: 'done' },
  { id: 80, section: 'P1 Voxel Editor', name: 'Reset cam', status: 'done' },
  { id: 81, section: 'P1 Voxel Editor', name: 'F-persp', status: 'done' },
  { id: 82, section: 'P1 Voxel Editor', name: 'Ortho', status: 'done' },
  { id: 83, section: 'P1 Voxel Editor', name: 'Voxel count', status: 'done' },
  { id: 84, section: 'P1 Voxel Editor', name: 'Face count', status: 'done' },
  { id: 85, section: 'P1 Voxel Editor', name: 'Mem warn', status: 'done' },
  { id: 86, section: 'P1 Voxel Editor', name: 'Autosnap', status: 'done' },
  { id: 87, section: 'P1 Voxel Editor', name: 'Ghost last stroke', status: 'done' },
  { id: 88, section: 'P1 Voxel Editor', name: 'Symmetry live', status: 'done' },
  { id: 89, section: 'P1 Voxel Editor', name: 'Starter cube', status: 'done' },
  { id: 90, section: 'P1 Voxel Editor', name: 'Starter item', status: 'done' },
  { id: 91, section: 'P1 Voxel Editor', name: 'Starter sword', status: 'done' },
  { id: 92, section: 'P1 Voxel Editor', name: 'Starter tool', status: 'done' },
  { id: 93, section: 'P1 Voxel Editor', name: 'Starter character', status: 'done' },
  { id: 94, section: 'P1 Voxel Editor', name: 'Starter quadruped', status: 'done' },
  { id: 95, section: 'P1 Voxel Editor', name: 'Starter bird', status: 'done' },
  { id: 96, section: 'P1 Voxel Editor', name: 'Starter dragon', status: 'done' },
  { id: 97, section: 'P1 Voxel Editor', name: 'Import PNG', status: 'done' },
  { id: 98, section: 'P1 Voxel Editor', name: 'Export PNG', status: 'done' },
  { id: 99, section: 'P1 Voxel Editor', name: 'Import .vxl', status: 'done' },
  { id: 100, section: 'P1 Voxel Editor', name: 'Export .vxl', status: 'done' },

  // ══ P2 BLOCKS 101–170 ══
  { id: 101, section: 'P2 Blocks', name: 'Display name', status: 'done' },
  { id: 102, section: 'P2 Blocks', name: 'Lore text', status: 'done' },
  { id: 103, section: 'P2 Blocks', name: 'Group/tab', status: 'done' },
  { id: 104, section: 'P2 Blocks', name: 'Max stack', status: 'done' },
  { id: 105, section: 'P2 Blocks', name: 'Opaque', status: 'done' },
  { id: 106, section: 'P2 Blocks', name: 'Transparent', status: 'done' },
  { id: 107, section: 'P2 Blocks', name: 'Cutout (leaves)', status: 'done' },
  { id: 108, section: 'P2 Blocks', name: 'Glass', status: 'done' },
  { id: 109, section: 'P2 Blocks', name: 'Light level 0–15', status: 'done' },
  { id: 110, section: 'P2 Blocks', name: 'Emission color', status: 'done' },
  { id: 111, section: 'P2 Blocks', name: 'Collision on/off', status: 'done' },
  { id: 112, section: 'P2 Blocks', name: 'Slipperiness', status: 'done' },
  { id: 113, section: 'P2 Blocks', name: 'Bounce', status: 'skipped', note: 'skip if no physics' },
  { id: 114, section: 'P2 Blocks', name: 'Gravity sand-like', status: 'skipped', note: 'skip if no physics' },
  { id: 115, section: 'P2 Blocks', name: 'Replaceable (air/grass)', status: 'done' },
  { id: 116, section: 'P2 Blocks', name: 'Break sound', status: 'done' },
  { id: 117, section: 'P2 Blocks', name: 'Place sound', status: 'done' },
  { id: 118, section: 'P2 Blocks', name: 'Step sound', status: 'done' },
  { id: 119, section: 'P2 Blocks', name: 'Hit sound', status: 'done' },
  { id: 120, section: 'P2 Blocks', name: 'Particle on break', status: 'done' },
  { id: 121, section: 'P2 Blocks', name: 'Tint grass', status: 'done' },
  { id: 122, section: 'P2 Blocks', name: 'Tint foliage', status: 'done' },
  { id: 123, section: 'P2 Blocks', name: 'Connects_to fence', status: 'skipped' },
  { id: 124, section: 'P2 Blocks', name: 'Waterlog', status: 'skipped' },
  { id: 125, section: 'P2 Blocks', name: 'Slab half', status: 'done' },
  { id: 126, section: 'P2 Blocks', name: 'Stairs', status: 'skipped', note: 'skip if mesher no stairs' },
  { id: 127, section: 'P2 Blocks', name: 'Log axis', status: 'done' },
  { id: 128, section: 'P2 Blocks', name: 'Bark all-sides', status: 'done' },
  { id: 129, section: 'P2 Blocks', name: 'Leaves decay', status: 'skipped' },
  { id: 130, section: 'P2 Blocks', name: 'Sapling', status: 'skipped' },
  { id: 131, section: 'P2 Blocks', name: 'Crop stages 0–7', status: 'skipped' },
  { id: 132, section: 'P2 Blocks', name: 'Door', status: 'skipped' },
  { id: 133, section: 'P2 Blocks', name: 'Trapdoor', status: 'skipped' },
  { id: 134, section: 'P2 Blocks', name: 'Fence', status: 'skipped' },
  { id: 135, section: 'P2 Blocks', name: 'Wall', status: 'skipped' },
  { id: 136, section: 'P2 Blocks', name: 'Pane', status: 'skipped' },
  { id: 137, section: 'P2 Blocks', name: 'Torch', status: 'done' },
  { id: 138, section: 'P2 Blocks', name: 'Lantern', status: 'done' },
  { id: 139, section: 'P2 Blocks', name: 'Chest 27', status: 'done' },
  { id: 140, section: 'P2 Blocks', name: 'Barrel 27', status: 'done' },
  { id: 141, section: 'P2 Blocks', name: 'Furnace', status: 'done' },
  { id: 142, section: 'P2 Blocks', name: 'Crafting table', status: 'done' },
  { id: 143, section: 'P2 Blocks', name: 'Ore', status: 'done' },
  { id: 144, section: 'P2 Blocks', name: 'Deepslate ore', status: 'done' },
  { id: 145, section: 'P2 Blocks', name: 'Raw block', status: 'done' },
  { id: 146, section: 'P2 Blocks', name: 'Storage mineral', status: 'done' },
  { id: 147, section: 'P2 Blocks', name: 'Planks', status: 'done' },
  { id: 148, section: 'P2 Blocks', name: 'Log', status: 'done' },
  { id: 149, section: 'P2 Blocks', name: 'Wood', status: 'done' },
  { id: 150, section: 'P2 Blocks', name: 'Stripped', status: 'skipped' },
  { id: 151, section: 'P2 Blocks', name: 'Dirt', status: 'done' },
  { id: 152, section: 'P2 Blocks', name: 'Grass', status: 'done' },
  { id: 153, section: 'P2 Blocks', name: 'Sand', status: 'done' },
  { id: 154, section: 'P2 Blocks', name: 'Gravel', status: 'done' },
  { id: 155, section: 'P2 Blocks', name: 'Stone', status: 'done' },
  { id: 156, section: 'P2 Blocks', name: 'Cobble', status: 'done' },
  { id: 157, section: 'P2 Blocks', name: 'Bricks', status: 'done' },
  { id: 158, section: 'P2 Blocks', name: 'Wool color 16', status: 'done' },
  { id: 159, section: 'P2 Blocks', name: 'Concrete 16', status: 'done' },
  { id: 160, section: 'P2 Blocks', name: 'Glass 16', status: 'done' },
  { id: 161, section: 'P2 Blocks', name: 'Carpet', status: 'skipped' },
  { id: 162, section: 'P2 Blocks', name: 'Pressure plate', status: 'skipped' },
  { id: 163, section: 'P2 Blocks', name: 'Button', status: 'skipped' },
  { id: 164, section: 'P2 Blocks', name: 'Lever', status: 'skipped' },
  { id: 165, section: 'P2 Blocks', name: 'Noteblock', status: 'skipped' },
  { id: 166, section: 'P2 Blocks', name: 'Bed', status: 'skipped' },
  { id: 167, section: 'P2 Blocks', name: 'Sign', status: 'skipped' },
  { id: 168, section: 'P2 Blocks', name: 'Item frame', status: 'skipped' },
  { id: 169, section: 'P2 Blocks', name: 'Spawner', status: 'skipped' },
  { id: 170, section: 'P2 Blocks', name: 'Custom model vs cube', status: 'done' },

  // ══ P3 ITEMS / TOOLS / ARMOR / FOOD 171–230 ══
  { id: 171, section: 'P3 Items', name: 'Item icon', status: 'done' },
  { id: 172, section: 'P3 Items', name: '2D vs 3D in hand', status: 'done' },
  { id: 173, section: 'P3 Items', name: 'Stack 1–64', status: 'done' },
  { id: 174, section: 'P3 Items', name: 'Durability', status: 'done' },
  { id: 175, section: 'P3 Items', name: 'Repair material', status: 'done' },
  { id: 176, section: 'P3 Items', name: 'Enchant', status: 'skipped' },
  { id: 177, section: 'P3 Items', name: 'Pickaxe', status: 'done' },
  { id: 178, section: 'P3 Items', name: 'Axe', status: 'done' },
  { id: 179, section: 'P3 Items', name: 'Shovel', status: 'done' },
  { id: 180, section: 'P3 Items', name: 'Hoe', status: 'skipped' },
  { id: 181, section: 'P3 Items', name: 'Sword', status: 'done' },
  { id: 182, section: 'P3 Items', name: 'Tier wood', status: 'done' },
  { id: 183, section: 'P3 Items', name: 'Tier stone', status: 'done' },
  { id: 184, section: 'P3 Items', name: 'Tier iron', status: 'done' },
  { id: 185, section: 'P3 Items', name: 'Tier custom', status: 'done' },
  { id: 186, section: 'P3 Items', name: 'Dig speed', status: 'done' },
  { id: 187, section: 'P3 Items', name: 'Damage', status: 'done' },
  { id: 188, section: 'P3 Items', name: 'Attack cooldown', status: 'done' },
  { id: 189, section: 'P3 Items', name: 'Knockback', status: 'done' },
  { id: 190, section: 'P3 Items', name: 'Sweep', status: 'skipped' },
  { id: 191, section: 'P3 Items', name: 'Helmet', status: 'done' },
  { id: 192, section: 'P3 Items', name: 'Chest', status: 'done' },
  { id: 193, section: 'P3 Items', name: 'Legs', status: 'done' },
  { id: 194, section: 'P3 Items', name: 'Boots', status: 'done' },
  { id: 195, section: 'P3 Items', name: 'Defense', status: 'done' },
  { id: 196, section: 'P3 Items', name: 'Armor toughness', status: 'skipped' },
  { id: 197, section: 'P3 Items', name: 'Set bonus', status: 'skipped' },
  { id: 198, section: 'P3 Items', name: 'Food hunger', status: 'done' },
  { id: 199, section: 'P3 Items', name: 'Saturation', status: 'done' },
  { id: 200, section: 'P3 Items', name: 'Eat time', status: 'done' },
  { id: 201, section: 'P3 Items', name: 'Always edible', status: 'done' },
  { id: 202, section: 'P3 Items', name: 'Raw meat', status: 'done' },
  { id: 203, section: 'P3 Items', name: 'Cooked meat', status: 'done' },
  { id: 204, section: 'P3 Items', name: 'Apple', status: 'done' },
  { id: 205, section: 'P3 Items', name: 'Bread', status: 'done' },
  { id: 206, section: 'P3 Items', name: 'Stew', status: 'skipped' },
  { id: 207, section: 'P3 Items', name: 'Seed', status: 'done' },
  { id: 208, section: 'P3 Items', name: 'Bone', status: 'done' },
  { id: 209, section: 'P3 Items', name: 'String', status: 'skipped' },
  { id: 210, section: 'P3 Items', name: 'Leather', status: 'done' },
  { id: 211, section: 'P3 Items', name: 'Stick', status: 'done' },
  { id: 212, section: 'P3 Items', name: 'Coal', status: 'done' },
  { id: 213, section: 'P3 Items', name: 'Charcoal', status: 'done' },
  { id: 214, section: 'P3 Items', name: 'Iron ingot', status: 'done' },
  { id: 215, section: 'P3 Items', name: 'Gold ingot', status: 'skipped', note: 'skip if no gold' },
  { id: 216, section: 'P3 Items', name: 'Diamond', status: 'skipped' },
  { id: 217, section: 'P3 Items', name: 'Fuel value', status: 'done' },
  { id: 218, section: 'P3 Items', name: 'Bucket', status: 'skipped' },
  { id: 219, section: 'P3 Items', name: 'Bow', status: 'skipped' },
  { id: 220, section: 'P3 Items', name: 'Shield', status: 'skipped' },
  { id: 221, section: 'P3 Items', name: 'Fishing', status: 'skipped' },
  { id: 222, section: 'P3 Items', name: 'Map', status: 'skipped' },
  { id: 223, section: 'P3 Items', name: 'Book', status: 'skipped' },
  { id: 224, section: 'P3 Items', name: 'Name tag', status: 'skipped' },
  { id: 225, section: 'P3 Items', name: 'Spawn egg', status: 'done' },
  { id: 226, section: 'P3 Items', name: 'Music disc', status: 'skipped' },
  { id: 227, section: 'P3 Items', name: 'Potion', status: 'skipped' },
  { id: 228, section: 'P3 Items', name: 'Custom use JSON', status: 'done' },
  { id: 229, section: 'P3 Items', name: 'Offhand', status: 'skipped' },
  { id: 230, section: 'P3 Items', name: 'Durability bar HUD', status: 'done' },

  // ══ P4 RECIPES / LOOT / SMELT 231–270 ══
  { id: 231, section: 'P4 Recipes', name: 'Shaped 3×3', status: 'done' },
  { id: 232, section: 'P4 Recipes', name: 'Shaped 2×2', status: 'done' },
  { id: 233, section: 'P4 Recipes', name: 'Shapeless', status: 'done' },
  { id: 234, section: 'P4 Recipes', name: 'Count output', status: 'done' },
  { id: 235, section: 'P4 Recipes', name: 'Group', status: 'done' },
  { id: 236, section: 'P4 Recipes', name: 'Unlock-all for now', status: 'done' },
  { id: 237, section: 'P4 Recipes', name: 'Furnace smelt', status: 'done' },
  { id: 238, section: 'P4 Recipes', name: 'Fuel tag', status: 'done' },
  { id: 239, section: 'P4 Recipes', name: 'Time ticks', status: 'done' },
  { id: 240, section: 'P4 Recipes', name: 'Campfire', status: 'skipped' },
  { id: 241, section: 'P4 Recipes', name: 'Smithing', status: 'skipped' },
  { id: 242, section: 'P4 Recipes', name: 'Stonecutter', status: 'skipped' },
  { id: 243, section: 'P4 Recipes', name: 'Loot block', status: 'done' },
  { id: 244, section: 'P4 Recipes', name: 'Loot rolls', status: 'done' },
  { id: 245, section: 'P4 Recipes', name: 'Loot weight', status: 'done' },
  { id: 246, section: 'P4 Recipes', name: 'Loot bonus chance', status: 'done' },
  { id: 247, section: 'P4 Recipes', name: 'Silk-touch', status: 'skipped' },
  { id: 248, section: 'P4 Recipes', name: 'Fortune', status: 'skipped' },
  { id: 249, section: 'P4 Recipes', name: 'Entity loot', status: 'done' },
  { id: 250, section: 'P4 Recipes', name: 'Chest loot prefab', status: 'done' },
  { id: 251, section: 'P4 Recipes', name: 'Fishing', status: 'skipped' },
  { id: 252, section: 'P4 Recipes', name: 'Gift', status: 'skipped' },
  { id: 253, section: 'P4 Recipes', name: 'Recipe book UI list', status: 'done' },
  { id: 254, section: 'P4 Recipes', name: 'Search recipes', status: 'done' },
  { id: 255, section: 'P4 Recipes', name: 'Ingredient tag #planks', status: 'done' },
  { id: 256, section: 'P4 Recipes', name: 'Ingredient tag #logs', status: 'done' },
  { id: 257, section: 'P4 Recipes', name: 'Ingredient tag #coals', status: 'done' },
  { id: 258, section: 'P4 Recipes', name: 'Custom tag', status: 'done' },
  { id: 259, section: 'P4 Recipes', name: 'Replace vanilla recipe', status: 'skipped' },
  { id: 260, section: 'P4 Recipes', name: 'Remove recipe', status: 'skipped' },
  { id: 261, section: 'P4 Recipes', name: 'Multi output', status: 'skipped' },
  { id: 262, section: 'P4 Recipes', name: 'Remainder bucket', status: 'skipped' },
  { id: 263, section: 'P4 Recipes', name: 'Crafting XP', status: 'skipped' },
  { id: 264, section: 'P4 Recipes', name: 'Smelt XP', status: 'skipped' },
  { id: 265, section: 'P4 Recipes', name: 'Recipe disabled flag', status: 'done' },
  { id: 266, section: 'P4 Recipes', name: 'Pack conflict last-wins', status: 'done' },
  { id: 267, section: 'P4 Recipes', name: 'Log conflicts', status: 'done' },
  { id: 268, section: 'P4 Recipes', name: 'Test craft in studio', status: 'done' },
  { id: 269, section: 'P4 Recipes', name: 'Test smelt in studio', status: 'done' },
  { id: 270, section: 'P4 Recipes', name: 'Dump all recipes JSON', status: 'done' },

  // ══ P5 MOBS 271–330 ══
  { id: 271, section: 'P5 Mobs', name: 'Id', status: 'done' },
  { id: 272, section: 'P5 Mobs', name: 'Name', status: 'done' },
  { id: 273, section: 'P5 Mobs', name: 'Model', status: 'done' },
  { id: 274, section: 'P5 Mobs', name: 'Texture', status: 'done' },
  { id: 275, section: 'P5 Mobs', name: 'Size', status: 'done' },
  { id: 276, section: 'P5 Mobs', name: 'Eye height', status: 'done' },
  { id: 277, section: 'P5 Mobs', name: 'HP', status: 'done' },
  { id: 278, section: 'P5 Mobs', name: 'Armor pts', status: 'skipped' },
  { id: 279, section: 'P5 Mobs', name: 'Speed', status: 'done' },
  { id: 280, section: 'P5 Mobs', name: 'Swim speed', status: 'skipped' },
  { id: 281, section: 'P5 Mobs', name: 'Fly', status: 'skipped' },
  { id: 282, section: 'P5 Mobs', name: 'Hostile', status: 'done' },
  { id: 283, section: 'P5 Mobs', name: 'Passive', status: 'done' },
  { id: 284, section: 'P5 Mobs', name: 'Neutral', status: 'done' },
  { id: 285, section: 'P5 Mobs', name: 'Melee dmg', status: 'done' },
  { id: 286, section: 'P5 Mobs', name: 'Range', status: 'done' },
  { id: 287, section: 'P5 Mobs', name: 'Cooldown', status: 'done' },
  { id: 288, section: 'P5 Mobs', name: 'Knockback', status: 'done' },
  { id: 289, section: 'P5 Mobs', name: 'i-frames', status: 'done' },
  { id: 290, section: 'P5 Mobs', name: 'Leap', status: 'skipped' },
  { id: 291, section: 'P5 Mobs', name: 'Night only', status: 'done' },
  { id: 292, section: 'P5 Mobs', name: 'Light max spawn', status: 'done' },
  { id: 293, section: 'P5 Mobs', name: 'Biome filter', status: 'done' },
  { id: 294, section: 'P5 Mobs', name: 'Weight', status: 'done' },
  { id: 295, section: 'P5 Mobs', name: 'Min pack', status: 'done' },
  { id: 296, section: 'P5 Mobs', name: 'Max pack', status: 'done' },
  { id: 297, section: 'P5 Mobs', name: 'Spawn on ground', status: 'done' },
  { id: 298, section: 'P5 Mobs', name: 'Not in water', status: 'done' },
  { id: 299, section: 'P5 Mobs', name: 'Not in lava', status: 'done' },
  { id: 300, section: 'P5 Mobs', name: 'Despawn', status: 'done' },
  { id: 301, section: 'P5 Mobs', name: 'Persistent flag', status: 'done' },
  { id: 302, section: 'P5 Mobs', name: 'Cap budget', status: 'done' },
  { id: 303, section: 'P5 Mobs', name: 'Hurt snd', status: 'done' },
  { id: 304, section: 'P5 Mobs', name: 'Death snd', status: 'done' },
  { id: 305, section: 'P5 Mobs', name: 'Idle snd', status: 'done' },
  { id: 306, section: 'P5 Mobs', name: 'Step snd', status: 'done' },
  { id: 307, section: 'P5 Mobs', name: 'Hit flash', status: 'done' },
  { id: 308, section: 'P5 Mobs', name: 'Death poof', status: 'done' },
  { id: 309, section: 'P5 Mobs', name: 'Drop table', status: 'done' },
  { id: 310, section: 'P5 Mobs', name: 'Rare drop', status: 'done' },
  { id: 311, section: 'P5 Mobs', name: 'XP', status: 'skipped' },
  { id: 312, section: 'P5 Mobs', name: 'Fire immune', status: 'skipped' },
  { id: 313, section: 'P5 Mobs', name: 'Freeze', status: 'skipped' },
  { id: 314, section: 'P5 Mobs', name: 'Sun burn', status: 'skipped' },
  { id: 315, section: 'P5 Mobs', name: 'Walk 2-frame', status: 'done' },
  { id: 316, section: 'P5 Mobs', name: 'Attack anim', status: 'done' },
  { id: 317, section: 'P5 Mobs', name: 'Idle anim', status: 'done' },
  { id: 318, section: 'P5 Mobs', name: 'Baby', status: 'skipped' },
  { id: 319, section: 'P5 Mobs', name: 'Tame', status: 'skipped' },
  { id: 320, section: 'P5 Mobs', name: 'Sit', status: 'skipped' },
  { id: 321, section: 'P5 Mobs', name: 'Breed', status: 'skipped' },
  { id: 322, section: 'P5 Mobs', name: 'Follow', status: 'skipped' },
  { id: 323, section: 'P5 Mobs', name: 'Ride', status: 'skipped' },
  { id: 324, section: 'P5 Mobs', name: 'Chest on ride', status: 'skipped' },
  { id: 325, section: 'P5 Mobs', name: 'Anger timer', status: 'done' },
  { id: 326, section: 'P5 Mobs', name: 'Call help', status: 'skipped' },
  { id: 327, section: 'P5 Mobs', name: 'Ranged', status: 'skipped' },
  { id: 328, section: 'P5 Mobs', name: 'Explosion', status: 'skipped' },
  { id: 329, section: 'P5 Mobs', name: 'Boss HP bar', status: 'done' },
  { id: 330, section: 'P5 Mobs', name: 'Boss extra AI', status: 'skipped' },

  // ══ P6 WORLD HOOKS 331–360 ══
  { id: 331, section: 'P6 World Hooks', name: 'Extra ore vein', status: 'done' },
  { id: 332, section: 'P6 World Hooks', name: 'minY', status: 'done' },
  { id: 333, section: 'P6 World Hooks', name: 'maxY', status: 'done' },
  { id: 334, section: 'P6 World Hooks', name: 'size', status: 'done' },
  { id: 335, section: 'P6 World Hooks', name: 'attempts/chunk', status: 'done' },
  { id: 336, section: 'P6 World Hooks', name: 'replace stone only', status: 'done' },
  { id: 337, section: 'P6 World Hooks', name: 'Surface block swap optional', status: 'done' },
  { id: 338, section: 'P6 World Hooks', name: 'Patch radius', status: 'done' },
  { id: 339, section: 'P6 World Hooks', name: 'Prefab .vxl', status: 'done' },
  { id: 340, section: 'P6 World Hooks', name: 'Prefab rarity', status: 'done' },
  { id: 341, section: 'P6 World Hooks', name: 'Prefab biome', status: 'done' },
  { id: 342, section: 'P6 World Hooks', name: 'Prefab on surface', status: 'done' },
  { id: 343, section: 'P6 World Hooks', name: 'Prefab origin', status: 'done' },
  { id: 344, section: 'P6 World Hooks', name: 'Grass tint', status: 'done' },
  { id: 345, section: 'P6 World Hooks', name: 'Foliage tint', status: 'done' },
  { id: 346, section: 'P6 World Hooks', name: 'Fog color', status: 'done' },
  { id: 347, section: 'P6 World Hooks', name: 'Fog density', status: 'done' },
  { id: 348, section: 'P6 World Hooks', name: 'Water tint', status: 'done' },
  { id: 349, section: 'P6 World Hooks', name: 'Sky', status: 'skipped' },
  { id: 350, section: 'P6 World Hooks', name: 'Time', status: 'skipped' },
  { id: 351, section: 'P6 World Hooks', name: 'Weather', status: 'skipped' },
  { id: 352, section: 'P6 World Hooks', name: 'Dimension', status: 'skipped', note: 'RULE: no dimensions' },
  { id: 353, section: 'P6 World Hooks', name: 'Structure village', status: 'skipped' },
  { id: 354, section: 'P6 World Hooks', name: 'Dungeon', status: 'skipped' },
  { id: 355, section: 'P6 World Hooks', name: 'Tree extra', status: 'skipped' },
  { id: 356, section: 'P6 World Hooks', name: 'Cave deco', status: 'skipped' },
  { id: 357, section: 'P6 World Hooks', name: 'Bedrock swap', status: 'skipped' },
  { id: 358, section: 'P6 World Hooks', name: 'Height overlay', status: 'skipped' },
  { id: 359, section: 'P6 World Hooks', name: 'World seed still owns terrain', status: 'done' },
  { id: 360, section: 'P6 World Hooks', name: 'Hook order documented', status: 'done' },

  // ══ P7 SAFE HOOKS 361–390 ══
  { id: 361, section: 'P7 Safe Hooks', name: 'onPlace', status: 'done' },
  { id: 362, section: 'P7 Safe Hooks', name: 'onBreak', status: 'done' },
  { id: 363, section: 'P7 Safe Hooks', name: 'onUse', status: 'done' },
  { id: 364, section: 'P7 Safe Hooks', name: 'onHit', status: 'done' },
  { id: 365, section: 'P7 Safe Hooks', name: 'onHurt', status: 'done' },
  { id: 366, section: 'P7 Safe Hooks', name: 'onEat', status: 'done' },
  { id: 367, section: 'P7 Safe Hooks', name: 'onCraft', status: 'done' },
  { id: 368, section: 'P7 Safe Hooks', name: 'onSmelt', status: 'done' },
  { id: 369, section: 'P7 Safe Hooks', name: 'onSpawn', status: 'done' },
  { id: 370, section: 'P7 Safe Hooks', name: 'onDeath', status: 'done' },
  { id: 371, section: 'P7 Safe Hooks', name: 'action giveItem', status: 'done' },
  { id: 372, section: 'P7 Safe Hooks', name: 'action takeItem', status: 'done' },
  { id: 373, section: 'P7 Safe Hooks', name: 'action hurt', status: 'done' },
  { id: 374, section: 'P7 Safe Hooks', name: 'action heal', status: 'done' },
  { id: 375, section: 'P7 Safe Hooks', name: 'action setBlock', status: 'done' },
  { id: 376, section: 'P7 Safe Hooks', name: 'action playSound', status: 'done' },
  { id: 377, section: 'P7 Safe Hooks', name: 'action openUi', status: 'done' },
  { id: 378, section: 'P7 Safe Hooks', name: 'action giveFood', status: 'done' },
  { id: 379, section: 'P7 Safe Hooks', name: 'No eval', status: 'done', note: 'Enforced' },
  { id: 380, section: 'P7 Safe Hooks', name: 'No Function', status: 'done', note: 'Enforced' },
  { id: 381, section: 'P7 Safe Hooks', name: 'No fetch', status: 'done', note: 'Enforced' },
  { id: 382, section: 'P7 Safe Hooks', name: 'No WebSocket', status: 'done', note: 'Enforced' },
  { id: 383, section: 'P7 Safe Hooks', name: 'Tick ≤1/s/mod', status: 'done' },
  { id: 384, section: 'P7 Safe Hooks', name: 'Tick off on Very Low', status: 'done' },
  { id: 385, section: 'P7 Safe Hooks', name: 'Error isolates hook', status: 'done' },
  { id: 386, section: 'P7 Safe Hooks', name: 'Hook debug log', status: 'done' },
  { id: 387, section: 'P7 Safe Hooks', name: 'Hook budget', status: 'done' },
  { id: 388, section: 'P7 Safe Hooks', name: 'JSON schema check', status: 'done' },
  { id: 389, section: 'P7 Safe Hooks', name: 'Example hook pack', status: 'done' },
  { id: 390, section: 'P7 Safe Hooks', name: 'Disable scripts global setting', status: 'done' },

  // ══ P8 AUDIO / FX / UI INGAME 391–420 ══
  { id: 391, section: 'P8 Audio & FX', name: 'One-shot sfx import wav/ogg', status: 'done' },
  { id: 392, section: 'P8 Audio & FX', name: 'Volume', status: 'done' },
  { id: 393, section: 'P8 Audio & FX', name: '3D distance', status: 'skipped', note: 'skip-if-hard' },
  { id: 394, section: 'P8 Audio & FX', name: 'Music', status: 'skipped' },
  { id: 395, section: 'P8 Audio & FX', name: 'Break particles', status: 'done' },
  { id: 396, section: 'P8 Audio & FX', name: 'Hit particles', status: 'done' },
  { id: 397, section: 'P8 Audio & FX', name: 'Place click', status: 'done' },
  { id: 398, section: 'P8 Audio & FX', name: 'UI click use title sfx', status: 'done' },
  { id: 399, section: 'P8 Audio & FX', name: 'Lang en', status: 'done' },
  { id: 400, section: 'P8 Audio & FX', name: 'Lang keys', status: 'done' },
  { id: 401, section: 'P8 Audio & FX', name: 'Item tooltip', status: 'done' },
  { id: 402, section: 'P8 Audio & FX', name: 'Block tooltip', status: 'done' },
  { id: 403, section: 'P8 Audio & FX', name: 'Advancements', status: 'skipped' },
  { id: 404, section: 'P8 Audio & FX', name: 'Map color', status: 'done' },
  { id: 405, section: 'P8 Audio & FX', name: 'Tab group Building', status: 'done' },
  { id: 406, section: 'P8 Audio & FX', name: 'Tab Redstone', status: 'skipped' },
  { id: 407, section: 'P8 Audio & FX', name: 'Tab Food', status: 'done' },
  { id: 408, section: 'P8 Audio & FX', name: 'Tab Tools', status: 'done' },
  { id: 409, section: 'P8 Audio & FX', name: 'Tab Combat', status: 'done' },
  { id: 410, section: 'P8 Audio & FX', name: 'Tab Mobs', status: 'done' },
  { id: 411, section: 'P8 Audio & FX', name: 'Creative search', status: 'done' },
  { id: 412, section: 'P8 Audio & FX', name: 'JEI-like recipe hover', status: 'done' },
  { id: 413, section: 'P8 Audio & FX', name: 'Hide from creative', status: 'done' },
  { id: 414, section: 'P8 Audio & FX', name: 'Glow item', status: 'skipped' },
  { id: 415, section: 'P8 Audio & FX', name: 'Enchant glint', status: 'skipped' },
  { id: 416, section: 'P8 Audio & FX', name: 'Custom hotbar badge', status: 'done' },
  { id: 417, section: 'P8 Audio & FX', name: 'Durability color', status: 'done' },
  { id: 418, section: 'P8 Audio & FX', name: 'Hunger restore numbers', status: 'done' },
  { id: 419, section: 'P8 Audio & FX', name: 'Damage popup', status: 'done' },
  { id: 420, section: 'P8 Audio & FX', name: 'Boss bar color', status: 'done' },

  // ══ P9 STUDIO APP 421–470 ══
  { id: 421, section: 'P9 Studio App', name: 'Overview', status: 'done' },
  { id: 422, section: 'P9 Studio App', name: 'My Mods cards', status: 'done' },
  { id: 423, section: 'P9 Studio App', name: 'Icon 64', status: 'done' },
  { id: 424, section: 'P9 Studio App', name: 'Create hub', status: 'done' },
  { id: 425, section: 'P9 Studio App', name: 'Assets', status: 'done' },
  { id: 426, section: 'P9 Studio App', name: 'Scripts view', status: 'done' },
  { id: 427, section: 'P9 Studio App', name: 'Testing picker', status: 'done' },
  { id: 428, section: 'P9 Studio App', name: 'Reload mods', status: 'done' },
  { id: 429, section: 'P9 Studio App', name: 'Hot reload textures', status: 'done' },
  { id: 430, section: 'P9 Studio App', name: 'Version major', status: 'done' },
  { id: 431, section: 'P9 Studio App', name: 'minor', status: 'done' },
  { id: 432, section: 'P9 Studio App', name: 'patch', status: 'done' },
  { id: 433, section: 'P9 Studio App', name: 'Changelog text', status: 'done' },
  { id: 434, section: 'P9 Studio App', name: 'Hide Analytics', status: 'done' },
  { id: 435, section: 'P9 Studio App', name: 'Publish checklist', status: 'done' },
  { id: 436, section: 'P9 Studio App', name: 'License field', status: 'done' },
  { id: 437, section: 'P9 Studio App', name: 'Credits Acaitart', status: 'done' },
  { id: 438, section: 'P9 Studio App', name: 'Pack format ver', status: 'done' },
  { id: 439, section: 'P9 Studio App', name: 'Search all', status: 'done' },
  { id: 440, section: 'P9 Studio App', name: 'Filters', status: 'done' },
  { id: 441, section: 'P9 Studio App', name: 'Dirty prompt', status: 'done' },
  { id: 442, section: 'P9 Studio App', name: 'Ctrl+S', status: 'done' },
  { id: 443, section: 'P9 Studio App', name: 'Ctrl+Z', status: 'done' },
  { id: 444, section: 'P9 Studio App', name: 'Ctrl+Y', status: 'done' },
  { id: 445, section: 'P9 Studio App', name: 'Ctrl+N', status: 'done' },
  { id: 446, section: 'P9 Studio App', name: 'Ctrl+O', status: 'done' },
  { id: 447, section: 'P9 Studio App', name: 'B brush', status: 'done' },
  { id: 448, section: 'P9 Studio App', name: 'E erase', status: 'done' },
  { id: 449, section: 'P9 Studio App', name: 'G pick', status: 'done' },
  { id: 450, section: 'P9 Studio App', name: 'F fill', status: 'done' },
  { id: 451, section: 'P9 Studio App', name: 'Space pan', status: 'done' },
  { id: 452, section: 'P9 Studio App', name: 'Alt rotate', status: 'done' },
  { id: 453, section: 'P9 Studio App', name: 'Guide tutorial', status: 'done' },
  { id: 454, section: 'P9 Studio App', name: 'Recipe examples', status: 'done' },
  { id: 455, section: 'P9 Studio App', name: 'Mob examples', status: 'done' },
  { id: 456, section: 'P9 Studio App', name: 'Validate id', status: 'done' },
  { id: 457, section: 'P9 Studio App', name: 'Unique id', status: 'done' },
  { id: 458, section: 'P9 Studio App', name: 'Atlas size warn', status: 'done' },
  { id: 459, section: 'P9 Studio App', name: 'PNG size warn', status: 'done' },
  { id: 460, section: 'P9 Studio App', name: 'Zip bomb guard', status: 'done' },
  { id: 461, section: 'P9 Studio App', name: 'Max 64 mods enabled', status: 'done' },
  { id: 462, section: 'P9 Studio App', name: 'Max 256 blocks/mod', status: 'done' },
  { id: 463, section: 'P9 Studio App', name: 'Max 256 items/mod', status: 'done' },
  { id: 464, section: 'P9 Studio App', name: 'Max 16 entities/mod', status: 'done' },
  { id: 465, section: 'P9 Studio App', name: 'One WebGL preview', status: 'done' },
  { id: 466, section: 'P9 Studio App', name: 'Pause preview when hidden', status: 'done' },
  { id: 467, section: 'P9 Studio App', name: 'Very Low preview', status: 'done' },
  { id: 468, section: 'P9 Studio App', name: '390px layout', status: 'done' },
  { id: 469, section: 'P9 Studio App', name: '1280px layout', status: 'done' },
  { id: 470, section: 'P9 Studio App', name: '44px targets', status: 'done' },

  // ══ P10 SHIP / QA / MP / PERF 471–500 ══
  { id: 471, section: 'P10 Ship & QA', name: 'World loads if mod missing', status: 'done' },
  { id: 472, section: 'P10 Ship & QA', name: 'Placeholder cube', status: 'done' },
  { id: 473, section: 'P10 Ship & QA', name: 'MP: peer missing mod', status: 'done' },
  { id: 474, section: 'P10 Ship & QA', name: 'MP: no script on server yet', status: 'done' },
  { id: 475, section: 'P10 Ship & QA', name: 'gfx Very Low disables extra entities', status: 'done' },
  { id: 476, section: 'P10 Ship & QA', name: 'Chunk budget unchanged', status: 'done' },
  { id: 477, section: 'P10 Ship & QA', name: 'No second renderer', status: 'done' },
  { id: 478, section: 'P10 Ship & QA', name: 'Test: place 100 custom blocks', status: 'done' },
  { id: 479, section: 'P10 Ship & QA', name: 'Test: reload page persist', status: 'done' },
  { id: 480, section: 'P10 Ship & QA', name: 'Test: disable mod, world still opens', status: 'done' },
  { id: 481, section: 'P10 Ship & QA', name: 'Test: import zip', status: 'done' },
  { id: 482, section: 'P10 Ship & QA', name: 'Test: export zip', status: 'done' },
  { id: 483, section: 'P10 Ship & QA', name: 'Test: recipe craft', status: 'done' },
  { id: 484, section: 'P10 Ship & QA', name: 'Test: smelt if furnace done', status: 'done' },
  { id: 485, section: 'P10 Ship & QA', name: 'Test: punch custom block drop', status: 'done' },
  { id: 486, section: 'P10 Ship & QA', name: 'Test: phone stack layout', status: 'done' },
  { id: 487, section: 'P10 Ship & QA', name: 'Test: file input styled', status: 'done' },
  { id: 488, section: 'P10 Ship & QA', name: 'Test: death+respawn still works', status: 'done' },
  { id: 489, section: 'P10 Ship & QA', name: 'Test: camera sensitivity untouched', status: 'done' },
  { id: 490, section: 'P10 Ship & QA', name: 'Docs in README Mods', status: 'done' },
  { id: 491, section: 'P10 Ship & QA', name: 'Example GoodVibes-based cobble', status: 'done' },
  { id: 492, section: 'P10 Ship & QA', name: 'Example food', status: 'done' },
  { id: 493, section: 'P10 Ship & QA', name: 'Example zombie-like', status: 'done' },
  { id: 494, section: 'P10 Ship & QA', name: 'Example ore vein', status: 'done' },
  { id: 495, section: 'P10 Ship & QA', name: 'Example prefab camp', status: 'done' },
  { id: 496, section: 'P10 Ship & QA', name: 'Conflict last-wins log', status: 'done' },
  { id: 497, section: 'P10 Ship & QA', name: 'Telemetry off', status: 'done' },
  { id: 498, section: 'P10 Ship & QA', name: 'No analytics backend', status: 'done' },
  { id: 499, section: 'P10 Ship & QA', name: 'Checklist 1–500 printed', status: 'done' },
  { id: 500, section: 'P10 Ship & QA', name: 'STOP and demo P0 if time runs out', status: 'done' },
];
