/** Honest visual-learning stage labels — never claim training without an adapter job. */

export type VytheraLearningStage =
  | 'REFERENCE_SAVED'
  | 'ADDED_TO_LEARNING_DATASET'
  | 'READY_FOR_TRAINING'
  | 'TRAINING_IN_PROGRESS'
  | 'MODEL_ADAPTED'
  | 'MODEL_EVALUATED'
  | 'MODEL_PROMOTED'
  | 'LOCAL_TRAINING_BACKEND_NOT_AVAILABLE'
  | 'LOCAL_TRAINING_READY';

export type VytheraTeachLifecycle =
  | 'IMPORTED'
  | 'ANALYZED'
  | 'CORRECTED'
  | 'APPROVED'
  | 'DATASET'
  | 'REJECTED';

export const LEARNING_STAGE_LABELS: Record<VytheraLearningStage, string> = {
  REFERENCE_SAVED: 'REFERENCE SAVED',
  ADDED_TO_LEARNING_DATASET: 'ADDED TO LEARNING DATASET',
  READY_FOR_TRAINING: 'READY FOR TRAINING',
  TRAINING_IN_PROGRESS: 'TRAINING IN PROGRESS',
  MODEL_ADAPTED: 'MODEL ADAPTED',
  MODEL_EVALUATED: 'MODEL EVALUATED',
  MODEL_PROMOTED: 'MODEL PROMOTED',
  LOCAL_TRAINING_BACKEND_NOT_AVAILABLE: 'LOCAL TRAINING BACKEND NOT AVAILABLE',
  LOCAL_TRAINING_READY: 'LOCAL TRAINING READY',
};
